at_2021/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('at/', include('at_project.urls')),
]

at_project/urls.py
from django.urls import path
from at_project.views import *

app_name = 'at_project'
urlpatterns = [
    # 경현
    path('k-food-report/', KFoodReportViews.as_view(), name='k-food-report'),
    path('recipe-ajax/', gy_views.recipe_ajax, name='recipe-ajax'),
    path('idol/', KFoodIdolViews.as_view(), name='idol'),
    path('food-recipe-2/', FoodRecipe2Views.as_view(), name='food-recipe-2'),
    path('test/', TableauTestViews.as_view(), name='test'),
    path('k-tour/', KTourViews.as_view(), name='k-tour'),
    path('k-tour-select/<str:id>', KTourSelectViews.as_view(), name='k-tour-select'),
    # path('k-tour/', AboutViews.as_view(), name='k-tour'),

    # 지원
    path('', IndexMainViews.as_view(), name='index'),
    path('k-food-report-2/', KFoodReport2Views.as_view(), name='k-food-report-2'),
    path('k-food-report-3/', KFoodReport3Views.as_view(), name='k-food-report-3'),
    path('k-food-report-4/', KFoodReport4Views.as_view(), name='k-food-report-4'),
    path('food-recipe-1/', FoodRecipe1Views.as_view(), name='food-recipe-1'),
    path('food-recipe-main/', FoodRecipeMainViews.as_view(), name='food-recipe-main'),
    path('food-recipe-detail/', FoodRecipeDetailViews.as_view(), name='food-recipe-detail'),
    path('food-recipe-detail-1/', FoodRecipeDetail1Views.as_view(), name='food-recipe-detail-1'),
    path('food-recipe-detail-2/', FoodRecipeDetail2Views.as_view(), name='food-recipe-detail-2'),
    path('food-recipe-detail-3/', FoodRecipeDetail3Views.as_view(), name='food-recipe-detail-3'),
    path('food-recipe-detail-4/', FoodRecipeDetail4Views.as_view(), name='food-recipe-detail-4'),
    path('food-recipe-detail-5/', FoodRecipeDetail5Views.as_view(), name='food-recipe-detail-5'),

    path('boards/', CommunityBoardsViews.as_view(), name='boards'),
    path('writing/', CommunityBoardsWritingViews.as_view(), name='boards-writing'),
    path('boards-test/', CommunityBoardsTestViews.as_view(), name='boards-test'),
]

at_project/models.py
from django.db import models

# Create your models here.

at_project/views/gy_views.py
import os

from django.shortcuts import render
from django.views.generic import View, TemplateView
from django.http import HttpResponse, JsonResponse
from bs4 import BeautifulSoup
import requests
import pandas as pd


class KFoodReportViews(TemplateView):
    template_name = "at_project/gy/k-food-report.html"


def recipe_ajax(request):
    if request.is_ajax():
        test = request.GET
        _url = ''.join(
            [f'{value}={test[value]}' if idx == 0 else f'&{value}={test[value]}' for idx, value in enumerate(test)])
        url = f'http://api.nongsaro.go.kr/service/{_url}'
        res = requests.get(url)
        soup = BeautifulSoup(res.content, 'html.parser')
        return HttpResponse(soup,
                            content_type='application/json')
    return render(request, 'at_project/gy/repice.html')


class KFoodIdolViews(TemplateView):
    template_name = "at_project/gy/k-food-idol.html"


class FoodRecipe2Views(TemplateView):
    template_name = "at_project/gy/food-recipe-2.html"


class TableauTestViews(TemplateView):
    template_name = "at_project/gy/tableau_test.html"


class KTourViews(TemplateView):
    def get_context_data(self):
        context = super().get_context_data()
        map = pd.read_csv('at_project/views/서울_맛집.csv', encoding='cp949')

        js = map.to_json(orient='records')
        context['map'] = js
        return context

    template_name = "at_project/gy/k-tour.html"


class KTourSelectViews(View):
    def get(self, request, id):
        return JsonResponse(self.get_data(id), safe=False)

    def get_data(self, id):
        print(id)
        _map = pd.read_csv('at_project/views/서울_맛집.csv', encoding='cp949')
        map = _map[_map['구'] == id]
        js = map.to_json(orient='records')
        return {'map': js}

at_project/views/jy_views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexMainViews(TemplateView):
    template_name = "at_project/jy/index.html"


class FoodRecipe1Views(TemplateView):
    template_name = "at_project/jy/food-recipe-1.html"


class KFoodReport2Views(TemplateView):
    template_name = "at_project/jy/k-food-report-2.html"

class KFoodReport3Views(TemplateView):
    template_name = "at_project/jy/k-food-report-3.html"

class KFoodReport4Views(TemplateView):
    template_name = "at_project/jy/k-food-report-4.html"

class FoodRecipeMainViews(TemplateView):
    template_name = "at_project/jy/food-recipe-main.html"

class FoodRecipeDetailViews(TemplateView):
    template_name = "at_project/jy/food-recipe-detail.html"

class FoodRecipeDetail1Views(TemplateView):
    template_name = "at_project/jy/food-recipe-detail-1.html"

class FoodRecipeDetail2Views(TemplateView):
    template_name = "at_project/jy/food-recipe-detail-2.html"

class FoodRecipeDetail3Views(TemplateView):
    template_name = "at_project/jy/food-recipe-detail-3.html"

class FoodRecipeDetail4Views(TemplateView):
    template_name = "at_project/jy/food-recipe-detail-4.html"

class FoodRecipeDetail5Views(TemplateView):
    template_name = "at_project/jy/food-recipe-detail-5.html"

class CommunityBoardsViews(TemplateView):
    # login_session = request.session.get('login_session', '')
    # context = {'login_session': login_session}
    # return render(request, "at_project/jy/boards.html", context)
    template_name =  "at_project/jy/boards.html"

class CommunityBoardsWritingViews(TemplateView):
    # login_session = request.session.get('login_session', '')
    # context = {'login_session': login_session}
    # return render(request, "at_project/jy/boards-writing.html", context)
    template_name = "at_project/jy/boards-writing.html"

class CommunityBoardsTestViews(TemplateView):
    # login_session = request.session.get('login_session', '')
    # context = {'login_session': login_session}
    # return render(request, "at_project/jy/boards.html", context)
    template_name =  "at_project/jy/boards-test.html"

at_project/templates/at_project/gy/k-food-report.html
{% extends '../__base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>K-FOOD-REPORT</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="">Home</a>
                        <span>Blog</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/kReport-main.PNG' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Report</div>
                                <ul>
                                    <li>By <span>James Myers</span></li>
                                    <li>13 Nov 2020</li>
                                    <li>112 Views</li>
                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <a href="{% url 'at_project:k-food-report-2' %}" style="text-transform: none;"><h2>Is Korean food<br/>popular abroad?</h2></a>
                            <p>Herbs are fun and easy to grow. When harvested they make even the simplest meal seem like
                                a gourmet delight. By using herbs in your cooking you can easily change the flavors of
                            your recipes in many different ways, according to which herbs you add...</p>
                            <a href="{% url 'at_project:k-food-report-2' %}">READ MORE</a>
                        </div>
                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/blog/blog-2.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Report</div>
                                <ul>
                                    <li>By <span>James Myers</span></li>
                                    <li>13 Nov 2020</li>
                                    <li>112 Views</li>
                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <h2>Make Grilling A Healthy Experience</h2>
                            <p>Herbs are fun and easy to grow. When harvested they make even the simplest meal seem like
                                a gourmet delight. By using herbs in your cooking you can easily change the flavors of
                            your recipes in many different ways, according to which herbs you add...</p>
                            <a href="#">READ MORE</a>
                        </div>
                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/blog/blog-3.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Report</div>
                                <ul>
                                    <li>By <span>James Myers</span></li>
                                    <li>13 Nov 2020</li>
                                    <li>112 Views</li>
                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <h2>Bbq Myths Getting You Down</h2>
                            <p>Herbs are fun and easy to grow. When harvested they make even the simplest meal seem like
                                a gourmet delight. By using herbs in your cooking you can easily change the flavors of
                            your recipes in many different ways, according to which herbs you add...</p>
                            <a href="#">READ MORE</a>
                        </div>
                    </div>
                    <div class="shop__pagination">
                        <a href="#">1</a>
{#                        <a href="#">2</a>#}
{#                        <a href="#">3</a>#}
                        <a href="#"><span class="arrow_carrot-right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__search">
                            <form action="#">
                                <input type="text" placeholder="Enter keyword">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        <div class="blog__sidebar__item">
                            <h5>Follow me</h5>
                            <div class="blog__sidebar__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h5>Popular posts</h5>

                            <div class="blog__sidebar__recent">
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-1.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Secret To Cooking Vegetables</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-2.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Bbq Myths Getting You Down</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-3.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Save Money The Crock Pot Way</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-4.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Grilling Tips For The Dog Days Of Summer</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-5.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Barbeque Techniques Two Methods To Consider</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                            </div>
                        </div>
{#                        <div class="blog__sidebar__item">#}
{#                            <h5>Categories</h5>#}
{#                            <div class="blog__sidebar__item__categories">#}
{#                                <ul>#}
{#                                    <li><a href="{% url 'at_project:recipe-ajax' %}">Repice <span>36</span></a></li>#}
{#                                    <li><a href="#">Guides <span>18</span></a></li>#}
{#                                    <li><a href="#">News <span>09</span></a></li>#}
{#                                    <li><a href="#">Videos <span>12</span></a></li>#}
{#                                    <li><a href="#">Trending <span>27</span></a></li>#}
{#                                </ul>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="blog__sidebar__item">
                            <h5>NEWsLETTeR</h5>
                            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <label for="agg">
                                    I agree to the terms & conditions
                                    <input type="checkbox" id="agg">
                                    <span class="checkmark"></span>
                                </label>
                                <button type="submit" class="site-btn">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock content %}

at_project/templates/at_project/gy/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

at_project/templates/at_project/jy/food-recipe-main.html
{% extends '../__base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>Recipes</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="{% url 'at_project:index' %}">Home</a>
                        <span>Blog</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/pastestew.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Recipes</div>
                                <ul>
                                    <li><span>된장찌개</span></li>
                                    <li>Soybean Paste Stew</li>
                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <p>
                            Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash. The broth is thick and flavorful, and good for mixing with rice.
                            </p>
                            <a href="{% url 'at_project:food-recipe-detail-1' %}">READ MORE</a>
                        </div>
                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/spicyStirFriedPork.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Recipes</div>
                                <ul>
                                    <li><span>제육볶음</span></li>
                                    <li>Stir-fried Pork</li>

                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <p>
                                Thinly sliced pork marinated in spicy ginger-gochujang and stir-fried with onion, carrots, perilla leaves, or abbage. Ingredients vary according to taste.</p>
                            <a href="{% url 'at_project:food-recipe-detail-2' %}">READ MORE</a>
                        </div>
                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/seafoodpajeon.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Recipes</div>
                                <ul>
                                    <li><span>해물파전</span></li>
                                    <li>Seafood and Green Onion Pancake</li>

                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <h2>Haemulpajeon</h2>
                            <p>
                            Julienned, tender young green onion stems folded into a flour batter with squid, clam meat, and oysters and pan-fried. Served with a soy vinaigrette dipping sauce.
                            </p>
                            <a href="{% url 'at_project:food-recipe-detail-3' %}">READ MORE</a>
                        </div>
                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/kimchijjigae.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Recipes</div>
                                <ul>
                                    <li><span>돼지고기 김치찌개</span></li>
                                    <li>Pork and Kimchi Stew</li>

                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <p>
                                Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean “soul food,” this spicy kimchi stew strikes a perfect balance with the greasy pork.
                            </p>
                            <a href="{% url 'at_project:food-recipe-detail-4' %}">READ MORE</a>
                        </div>

                    </div>
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{% static 'img/samgyetang-recipe.jpg' %}">
                            <div class="blog__pic__inner">
                                <div class="label">Recipes</div>
                                <ul>
                                    <li><span>삼계탕</span></li>
                                    <li>Ginseng Chicken Soup</li>
                                </ul>
                            </div>
                        </div>
                        <div class="blog__item__text">
                            <h2></h2>
                            <p>
                            Tender, whole, young chicken stuffed with ginseng, jujubes, sweet rice, and whole garlic cloves and simmered until tender. The combination of chicken and ginseng creates a complex yet harmonious flavor. This is a classic summertime dish that revitalizes the body and soul.
                            </p>
                            <a href="{% url 'at_project:food-recipe-detail-5' %}">READ MORE</a>
                        </div>

                    </div>
                    <div class="shop__pagination">
                        <a href="#">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a href="#"><span class="arrow_carrot-right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__search">
                            <form action="#">
                                <input type="text" placeholder="Enter keyword">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        <div class="blog__sidebar__item">
                            <h5>Follow me</h5>
                            <div class="blog__sidebar__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h5>Popular posts</h5>

                            <div class="blog__sidebar__recent">
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-1.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Secret To Cooking Vegetables</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-2.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Bbq Myths Getting You Down</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-3.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Save Money The Crock Pot Way</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-4.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Grilling Tips For The Dog Days Of Summer</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{% static 'img/blog/br-5.jpg' %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h4>Barbeque Techniques Two Methods To Consider</h4>
                                        <span>13 Nov 2020</span>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h5>NEWsLETTeR</h5>
                            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <label for="agg">
                                    I agree to the terms & conditions
                                    <input type="checkbox" id="agg">
                                    <span class="checkmark"></span>
                                </label>
                                <button type="submit" class="site-btn">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock content %}